### ISSUE TITLE
[객사오] 01장: 협력하는 객체들의 공동체

### ISSUE THREAD

**Issue by minjumost** [oop-book-study/study#1]
책을 읽으면서 배운 점, 궁금한 점, 나눠보고 싶은 이야기 등을 자유롭게 적어주세요.
이때 자신의 이야기에만 집중 하지 말고, 타인의 이야기에도 경청해주세요.
코멘트를 남겨야 한다는 강박보다는, 자유롭게 의견을 나누며 다양한 시각을 이해하고 
인사이트를 얻는 과정이 되기를 바랍니다.

**사소한 문제라도 고민이 된다면 적극적으로 의견을 얘기합시다.**

**Comment by ghrbs0437** [comment]
33p.
객체는 상태와 행위를 하나의 단위로 묶는 자율적 존재

라는 표현이 있어요. 

제가 생각하는 객체지향의 핵심을 관통하는 표현인것 같아요.


이와 반대인, 그렇지 않은 경우(객체의 설계)는 객체지향적이지 못한 것이고

= 1. 상태와 행위가 하나의 단위가 아닌 여러곳에 퍼져있는 
= 2. 여러 클래스가 상호 의존적인 
= 3. 클래스간의 결합도가 높은

동치라고 생각했습니다.

**Comment by becooq81** [comment]
객체에 대한 책인데 1장 내내 클래스 얘기가 없다는 생각이 문득 들 때 쯤 클래스와 객체의 오해에 대해 언급하시더라구요.
저는 주로 Java를 사용해서인지 객체가 곧 클래스다라고 무의식 중에 생각했었는데.. 중요한 것은 '객체를 어떻게 클래스로 표현할까?'가 아니라, '객체의 역할, 책임, 협력을 어떻게 코드로 표현할까?'인 것 같아요. 
이런 접근으로 짠 코드는 어떻게 다를까? 기대도 되고, Java로 코드를 짜면 결국 비슷해지지 않을까 라는 생각도 들지만 결국 핵심은 '어떤 가치관과 의도를 담아 코드를 짰는지'라고 생각해요.

**Comment by 10hajin15** [comment]
1. 1장의 마지막 챕터 "객체 지향의 본질  / 객체를 지향하라"를 읽고, 지금까지 저도 "객체지향 = 클래스지향"이라는 편견에 사로잡혀 있었던 것 같습니다. 책에서도 예시가 있듯이 JS는 **프로토타입** 기반의 객체 지향 언어입니다. 하지만 이후 es6버전에서 class 문법이 생겼는데 이와 관련해 객체 지향 프로그래밍에서 `class`가 왜 객체 지향의 원칙을 지키는데 다른 것으로 대체하지 못할 정도로 견고한, 유용한 방법인지 차차 알아나가고 싶어요.

2. 객체지향 프로그래밍도 결국 프로그래밍 패러다임이고 절차지향 프로그래밍의 한계를 극복하고자 나온 방식으로 알고 있어요. 책에서도 "메서드와 자율성 p.34" 파트에서 절차적인 언어와 구분되는 특징을 언급하는 것을 보고, "절차적 프로그래밍 -> 구조적 프로그래밍 -> 객체지향 프로그래밍 -> 함수형 프로그래밍" 여러 프로그래밍 패러다임이 등장하게 된 배경, 특징 등을 중심으로 이해하면 좀 더 잘 와닿을거라는 생각이 들었습니다. 그래서 이 책을 다 읽고 여러 프로그래밍 방식에 대해 함께 이야기 나눠보면 좋을 것 같아요~~!

**Comment by minjumost** [comment]
늦게 올려서 죄송합니다. 늦게나마 의견남깁니다.
저는 객체를 클래스로 바라보고 있었어요. 왜냐하면 자바 뿐아니라 타입스크립트도 사용하며 사실상 객체 없이는 코딩 하지 않았기 때문이죠.
> 객체는 클래스가 아니다. 

라는 말을 보며 '그럼 도대체 뭐가 객체야?' 라고 생각했고 1장에서 그 의문이 모두 풀리지는 않겠지만 일단 제가 이해한 바로는  객체지향을 바라볼때 클래스의 구조 메서드에 집중하는 것이 아니라 각 클래스들이 어떻게 관계를 가지는지, 역할과 책임 그리고 협력의 관점에서 바라보는 것이 좋겠다. 라는 생각을 하게 됐습니다. 
솔직히 1장만 읽었을때 까지는 감이 안잡히네요. 
객체지향 스터디가 완전히 새로운 지식을 배운다기 보다는 객체에 대한 스스로의 생각과 관점을 세우고 말할 수 있는 시간이 됐으면 좋겠습니다.
